var figures = [
    {
        id: "authors",
        path: "./images/authors.png",
        name: "Authors having a typical Amazonian meal with freshly caught fish with plantain at Huarmi Isla II Zona. Photo by Carlos Rengifo.",
        alt: "The three authors sitting on a bench having a typical Amazonian meal with freshly caught fish with plantain.",
        lat: "-5.0330620",
        lng: "-74.0752870",
        size: "",
    },
    {
        id: "1",
        path: "./images/figure1.jpg",
        name: "Carlos, our guide, waving from the bow of the Carlitos, near Oceanía. Photo by Christian Abizaid.",
        alt: "A guide is waving from the bow of the boat docked on a beach.",
        lat: "-5.8292040",
        lng: "-74.6963040",
        size: "",
    },
    {
        id: "2",
        path: "./images/figure2.png",
        name: "Route down the Ucayali and Amazon rivers from Pucallpa to Iquitos, June 2018.",
        alt: "Map of the route",
        lat: "",
        lng: "",
        size: "large",
    },
    {
        id: "2a",
        path: "./images/figure2a.png",
        name: "Pucallpa, a rapidly growing city fueled by trade and logging. Economic opportunities attract migrants from San Martín and Huánuco, giving this Amazonian city an Andean flavor. Photos by Oliver T. Coomes and Christian Abizaid.",
        alt: "",
        lat: "-8.3835280",
        lng: "-74.5308970",
        size: "",
    },
    {
        id: "2b",
        path: "./images/figure2b.png",
        name: "Iquitos. With close to half a million inhabitants, Iquitos is the largest city in the Peruvian Amazon. The importance of Iquitos as a trading center during the rubber boom in the late 19th and early 20th century is still evident in the city’s tiled mansions and trading houses built by the rubber barons. Iquitos has no road connection to the rest of the country and is increasingly becoming a hub for ecotourism and ‘healing tourism’ based on ayahuasca. Photos by Christian Abizaid and Oliver T. Coomes.",
        alt: "",
        lat: "-3.7491070",
        lng: "-73.2446420",
        size: "",
    },
    {
        id: "2c",
        path: "./images/figure2c.png",
        name: "Contamana, the Pearl of the Ucayali. Photos by Christian Abizaid and Oliver T. Coomes.",
        alt: "",
        lat: "-7.34782512",
        lng: "-75.0055074",
        size: "",
    },
    {
        id: "2d",
        path: "./images/figure2d.png",
        name: "Orellana. Photos by Christian Abizaid.",
        alt: "",
        lat: "-6.9112580",
        lng: "-75.1575870",
        size: "",
    },
    {
        id: "2e",
        path: "./images/figure2e.png",
        name: "Requena is the third largest city in Loreto. It is also known as the Athens of the Ucayali because it had several prestigious schools. Photos by Christian Abizaid.",
        alt: "",
        lat: "-5.0495540",
        lng: "-73.8297670",
        size: "",
    },
    {
        id: "2f1",
        path: "./images/figure2f1.jpg",
        name: "Rural communities along the Ucayali. Isla Baños and Huacrachiro. Photos: Christian Abizaid.",
        alt: "",
        lat: "-6.9591790",
        lng: "-75.0937700",
        size: "",
    },
    {
        id: "2f2",
        path: "./images/figure2f2.jpg",
        name: "Rural communities along the Ucayali. Isla Baños and Huacrachiro. Photos: Christian Abizaid.",
        alt: "",
        lat: "-6.959179",
        lng: "-75.093770",
        size: "",
    },
    {
        id: "3",
        path: "./images/figure3.gif",
        name: "A Google Engine time lapse of the Ucayali River near Pucallpa, based on Landsat imagery between 1984 and 2018",
        alt: "A time lapse of the flow of the Ucayali River between 1984 and 2018",
        lat: "",
        lng: "",
        size: "",
    },
    {
        id: "4",
        path: "./images/figure4.jpg",
        name: "A floating pen filled with live fish near Tamanco, drifting to Iquitos some 400 kilometers downriver. Photo by Yoshito Takasaki.",
        alt: "",
        lat: "-5.7961490",
        lng: "-74.2835550",
        size: "",
    },
    {
        id: "5",
        path: "./images/figure5.jpg",
        name: "Lanchas on the Ucayali like the Henry 4 shown here, transport anything from trucks and containers, to sacks of cement, water tanks, racemes of plantains, Andean potatoes, grapes from the Pacific coast, live animals, timber, fish in ice boxes made from old fridges, and much more; they have some cabins but most passengers hang hammocks on the deck to endure the tortuous journey. Without external supplies transported on these boats, a city lacking road access like Iquitos (pop. ~400,000) would have a hard time surviving. Photo by Oliver T. Coomes.",
        alt: "",
        lat: "",
        lng: "",
        size: "",
    },
    {
        id: "6",
        path: "./images/figure6.jpg",
        name: "Colectivo boats on the Ucayali River. Photos by Christian Abizaid and Yoshito Takasaki.",
        alt: "",
        lat: "",
        lng: "",
        size: "",
    },
    {
        id: "7",
        path: "./images/figure7.jpg",
        name: "A Peque-peque. The vernacular name for these motors is related to the noise they make, as they often lack a muffler. The long shaft from the engine to the propeller, locally called  “the tail”, facilitates navigation along smaller channels that are sinuous, shallow and filled with debris. Boats equipped with a small peque-peque motor can be easily operated by women and children. Photo by Yoshito Takasaki.",
        alt: "",
        lat: "",
        lng: "",
        size: "",
    },
    {
        id: "8",
        path: "./images/figure8.jpg",
        name: "A rápido. These long metal speedboats were originally used to transport goods and personnel during the construction of the Camisea Gas project in the early 2000s. Photo by Yoshito Takasaki.",
        alt: "",
        lat: "near tamanco",
        lng: "",
        size: "",
    },
    {
        id: "9",
        path: "./images/figure9.png",
        name: "Large cargo boats along the Ucayali. It is this type of vessels that the Hidrovía initiative aims to benefit, not local peoples. Photos by the authors.",
        alt: "",
        lat: "Ucayali River",
        lng: "",
        size: "",
    },
    {
        id: "10",
        path: "./images/figure10.jpg",
        name: "Road creeping westward behind Tierra Blanca towards the Huallaga River. Photo by Christian Abizaid. ",
        alt: "",
        lat: "-6.5607860",
        lng: "-75.1741050",
        size: "",
    },
    {
        id: "11",
        path: "./images/figure11.jpg",
        name: "Logging camp close to Isla Baños. Photos by Yoshito Takasaki.",
        alt: "",
        lat: "-6.9642860",
        lng: "-75.1160890",
        size: "",
    },
    {
        id: "12",
        path: "./images/figure12.gif",
        name: "Google Engine lapse of logging road extending eastwards to the Tapiche River and the Sierra del Divisor National Park, based on Landsat imagery between 2010 and 2018. ",
        alt: "",
        lat: "",
        lng: "",
        size: "",
    },
    {
        id: "13",
        path: "./images/figure13.jpg",
        name: "Rural road between San Cristobal and Dos de Mayo. Photo by Oliver T. Coomes.",
        alt: "",
        lat: "-6.3478380",
        lng: "-75.1171940",
        size: "small",
    },
    {
        id: "14",
        path: "./images/figure14.jpg",
        name: "Oliver Coomes indicating the highest flood level recorded by people in a riverine community near Pucallpa. Locals typically make marks on trees or buildings to keep a local record. Photo by Yoshito Takasaki.",
        alt: "",
        lat: "",
        lng: "",
        size: "",
    },
    {
        id: "15",
        path: "./images/figure15.jpg",
        name: "A rice field damaged by a recent repiquete at Las Brisas. Photo by Christian Abizaid.",
        alt: "",
        lat: "",
        lng: "",
        size: "",
    },
    {
        id: "16",
        path: "./images/figure16.jpg",
        name: "Home on high stilts. Huarmi Isla I. Photo by Oliver T. Coomes.",
        alt: "",
        lat: "-5.0682800",
        lng: "-74.0657480",
        size: "",
    },
    {
        id: "17",
        path: "./images/figure17.jpg",
        name: "Flood protection wall at San Carlos. Photo by Yoshito Takasaki",
        alt: "",
        lat: "-5.3330320",
        lng: "-74.3682950",
        size: "",
    },
    {
        id: "18",
        path: "./images/figure18.jpg",
        name: "A small shop selling peque-peques, chainsaws, generators and other gas motors at the port in Requena. Photo by Oliver T. Coomes. ",
        alt: "",
        lat: "-5.0495540",
        lng: "-73.8297670",
        size: "",
    },
    {
        id: "19",
        path: "./images/figure19.jpg",
        name: "A motokar used to haul water from the Ucayali for household use. A kubota driven back from the river’s edge to fetch the next load; a Chinese furgon parked on a hill. Photos by Christian Abizaid and Yoshito Takasaki.",
        alt: "",
        lat: "",
        lng: "",
        size: "",
    },
    {
        id: "20",
        path: "./images/figure20.jpg",
        name: "Small fishing boats with ice boxes bringing their catch to sell in Orellana. Photo by Oliver T. Coomes. ",
        alt: "",
        lat: "-6.9112580",
        lng: "-75.1575870",
        size: "",
    },
    {
        id: "21",
        path: "./images/figure21.jpg",
        name: "A man weeding a soccer field with a weed-eater at Tamanco. Photos by Christian Abizaid.",
        alt: "",
        lat: "-5.7961490",
        lng: "-74.2835550",
        size: "",
    },
    {
        id: "22",
        path: "./images/figure22.jpg",
        name: "A group of men building a boat at Alto Perillo and a small sawmill in Nuevo Canchahuaya. Photos by Yoshito Takasaki and Oliver T. Coomes.",
        alt: "",
        lat: "-7.0792470",
        lng: "-75.1530940",
        size: "small",
    },
    {
        id: "23",
        path: "./images/figure23.jpg",
        name: "A local business in Juancito offering cell phone-based money transfers. Photo by Christian Abizaid.",
        alt: "",
        lat: "-6.0429200",
        lng: "-74.8605820",
        size: "small",
    },
    {
        id: "24",
        path: "./images/figure24.jpg",
        name: "One of several fishing camps we encountered along the Ucayali River. Photo by Yoshito Takasaki. ",
        alt: "",
        lat: "",
        lng: "",
        size: "",
    },
    {
        id: "25",
        path: "./images/figure25.jpg",
        name: "Fisherman at Nuevo Mundo, waiting on a sandbar for the mijanos to pass by. Photo by Christian Abizaid.",
        alt: "",
        lat: "-5.7298880",
        lng: "-74.4616440",
        size: "",
    },
    {
        id: "other1",
        path: "./images/other1.jpg",
        name: "Bird drying its wings on a beach. Photo by Yoshito Takasaki.",
        alt: "",
        lat: "-5.6479910",
        lng: "-74.6720920",
        size: "small",
    },
    {
        id: "other2",
        path: "./images/other2.jpg",
        name: "Christian Abizaid playing foosball with local children in Juancito. Photo by Yoshito Takasaki.",
        alt: "",
        lat: "-6.042920",
        lng: "-74.860582",
        size: "small",
    },
    {
        id: "other3",
        path: "./images/other3.jpg",
        name: "Children playing volleyball. Photo by Christian Abizaid.",
        alt: "",
        lat: "",
        lng: "",
        size: "small",
    },
    {
        id: "other4",
        path: "./images/other4.jpg",
        name: "Girls on their way to school. Photo by Oliver T. Coomes.",
        alt: "",
        lat: "",
        lng: "",
        size: "small",
    },
    {
        id: "other5",
        path: "./images/other5.jpg",
        name: "A boat at dusk on Lake Yarinacocha, close to Pucallpa. Photo by Oliver T. Coomes.",
        alt: "",
        lat: "",
        lng: "",
        size: "small",
    },
    {
        id: "other6",
        path: "./images/other6.jpg",
        name: "The Ucayali River Photo by Christian Abizaid",
        alt: "",
        lat: "",
        lng: "",
        size: "small",
    },
    {
        id: "other7",
        path: "./images/other7.jpg",
        name: "A traditional fisherman showing his spear and catch. Photo by Christian Abizaid.",
        alt: "",
        lat: "",
        lng: "",
        size: "small",
    },
    {
        id: "other8",
        path: "./images/other8.jpg",
        name: "Fishermen Photo by Yoshito Takasaki.",
        alt: "",
        lat: "",
        lng: "",
        size: "small",
    },
    {
        id: "other9",
        path: "./images/other9.jpg",
        name: "Colorful houses along the Amazon Photo by Christian Abizaid",
        alt: "",
        lat: "",
        lng: "",
        size: "small",
    },
    {
        id: "other10",
        path: "./images/other10.jpg",
        name: "Rice field on another mudlfat. Photo by Christian Abizaid.",
        alt: "",
        lat: "-7.885044",
        lng: "-74.745477",
        size: "small",
    },
    {
        id: "other11",
        path: "./images/other11.jpg",
        name: "Cowpeas planted on a mudflat. Photo by Yoshito Takasaki.",
        alt: "",
        lat: "-7.617290961",
        lng: "-74.2835550",
        size: "small",
    },
    {
        id: "video1",
        path: "",
        name: "Travelling to Nuevo Encanto de Suni. Video by Yoshito Takasaki.",
        alt: "",
        lat: "-7.617291",
        lng: "-74.942159",
        size: "",
    },
    {
        id: "video2",
        path: "",
        name: "Riding a motokar in Pucallpa. Video by Yoshito Takasaki.",
        alt: "",
        lat: "-8.3835280",
        lng: "-74.5308970",
        size: "",
    },
    {
        id: "video3",
        path: "",
        name: "A furgon loaded with hardwood. Video by Yoshito Takasaki",
        alt: "",
        lat: "-7.3502890",
        lng: "-75.0091230",
        size: "",
    },
    {
        id: "video4",
        path: "",
        name: "A rapido leaving Pucallpa. Video by Yoshito Takasaki",
        alt: "",
        lat: "-8.3835280",
        lng: "-74.5308970",
        size: "",
    },
    {
        id: "video5",
        path: "",
        name: "Port at Pucallpa. Video by Yoshito Takasaki",
        alt: "",
        lat: "-8.3835280",
        lng: "-74.5308970",
        size: "",
    },
    {
        id: "video6",
        path: "",
        name: "Boats at the waterfront, Pucallpa. Video by Yoshito Takasaki",
        alt: "",
        lat: "-8.3835280",
        lng: "-74.5308970",
        size: "",
    },
    {
        id: "video7",
        path: "",
        name: "Road behind Tierra Blanca. Video by Yoshito Takasaki.",
        alt: "",
        lat: "-6.5607860",
        lng: "-75.1741050",
        size: "",
    },
    {
        id: "video8",
        path: "",
        name: "People watching Peru's national team during the World Cup. Video by Yoshito Takasaki",
        alt: "",
        lat: "-6.5607860",
        lng: "-75.1741050",
        size: "",
    },
    {
        id: "video9",
        path: "",
        name: "Young boys playing soccer. Video by Yoshito Takasaki",
        alt: "",
        lat: "",
        lng: "",
        size: "",
    },
    {
        id: "video10",
        path: "",
        name: "Arriving to Requena by boat. Video by Christian Abizaid",
        alt: "",
        lat: "-5.0495540",
        lng: "-73.8297670",
        size: "",
    },
    {
        id: "video11",
        path: "",
        name: "On the Pacaya River, PSNR.Video by Christian Abizaid",
        alt: "",
        lat: "-5.2453780",
        lng: "-74.3897730",
        size: "",
    },
    {
        id: "video12",
        path: "",
        name: "Travelling on a tributary towards Tamanco. Video by Christian Abizaid",
        alt: "",
        lat: "-5.7961490",
        lng: "-74.2835550",
        size: "",
    },
    {
        id: "video13",
        path: "",
        name: "Riverbank slumping along the Ucayali. Video by Christian Abizaid",
        alt: "",
        lat: "",
        lng: "",
        size: "",
    },
    {
        id: "video14",
        path: "",
        name: "On the Ucayali. Video by Christian Abizaid",
        alt: "",
        lat: "",
        lng: "",
        size: "",
    },
    {
        id: "video15",
        path: "",
        name: "Storm brewing over the Rio Amazonas. Video by Yoshito Takasaki",
        alt: "",
        lat: "",
        lng: "",
        size: "",
    },
    {
        id: "video16",
        path: "",
        name: "Boat ride from the Suni creek into the Ucayali River. Video by Yoshito Takasaki.",
        alt: "",
        lat: "",
        lng: "",
        size: "",
    },
    {
        id: "video17",
        path: "",
        name: "Traveling down the Ucayali 1. Video by Yoshito Takasaki.",
        alt: "",
        lat: "",
        lng: "",
        size: "",
    },
    {
        id: "video18",
        path: "",
        name: "Traveling down the Ucayali 2. Video by Yoshito Takasaki.",
        alt: "",
        lat: "",
        lng: "",
        size: "",
    },
    {
        id: "pucallpa",
        path: "",
        alt: "",
        lat: "-8.37851117630663",
        lng: "-74.59133795686964",
        size: "",
    },
    {
        id: "iquitos",
        path: "",
        alt: "",
        lat: "-3.755623480015298",
        lng: "-73.25777062761264",
        size: "",
    },
];
